// Collection to store metadata of uploaded audio/video files
import mongoose from "mongoose";

const { Schema, model } = mongoose;

// 🎯 TypeScript interface for type inference
export interface IMediaFile {
	_id: mongoose.Types.ObjectId | string; // Auto-generated by MongoDB
	filename: string;
	filePath: string;
	fileType: "audio" | "video";
	durationSec?: number;
	status: "in-progress" | "complete" | "error" | "processing";
	processingStatus?: "idle" | "processing" | "complete" | "error";
	language: string;
	transcript?: {
		language: string;
		language_probability: number;
		duration: number;
		segments: Array<{
			start: number;
			end: number;
			text: string;
			words?: Array<{
				start: number;
				end: number;
				word: string;
			}>;
			category?: "EXTREMIST_SPEECH" | "BAD_LANGUAGE";
		}>;
	};
	createdAt: Date;
	updatedAt: Date;
}

const mediaFileSchema = new Schema<IMediaFile>(
	{
		// Don't define _id - let MongoDB auto-generate it
		filename: { type: String, required: true },
		filePath: { type: String, required: true },
		fileType: { type: String, enum: ["audio", "video"], required: true },
		durationSec: { type: Number },
		status: {
			type: String,
			enum: ["in-progress", "complete", "error", "processing"],
			default: "in-progress",
		},
		processingStatus: {
			type: String,
			enum: ["idle", "processing", "complete", "error"],
			default: "idle",
		},
		language: { type: String, required: true, default: "en" },
		transcript: { type: Schema.Types.Mixed },
	},
	{
		collection: "media_files",
		timestamps: true,
	}
);

const MediaFile = model<IMediaFile>("MediaFile", mediaFileSchema);

export { MediaFile };
