import mongoose from "mongoose";

const { Schema, model } = mongoose;

// 🎯 TypeScript interface for type inference
export interface IStudent {
	_id: mongoose.Types.ObjectId | string; // Auto-generated by MongoDB
	name: string;
	studentNumber: number;
	email: string;
	createdAt: Date;
	updatedAt: Date;
}

const studentSchema = new Schema<IStudent>(
	{
		// Don't define _id - let MongoDB auto-generate it
		name: { type: String, required: true },
		studentNumber: { type: Number, required: true },
		email: { type: String, required: true },
		createdAt: { type: Date, required: true },
		updatedAt: { type: Date, required: true },
	},
	{ collection: "student" }
);

const Student = model<IStudent>("Student", studentSchema);

export { Student };
